Models/ErrorViewModel.cs
namespace SysMaster.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/StatusViewModel.cs
namespace SysMaster.Models
{
    public class StatusViewModel
    {

        public string CpuName { get; set; }
        public int CpuCores { get; set; }
        public string OsName { get; set; }
        public string FrameworkVersion { get; set; }
        public string RamMemory { get; set; }
        public string DownloadSpeed { get; set; }
        public string UploadSpeed { get; set; }
        public string Webcam { get; set; }
        public string MaquinaNome { get; set; }
        public string CaminhoFisico { get; set; }
        public string RamInstalada { get; set; }
        public string DiscoDisponivel { get; set; }
        public string DiscoTotal { get; set; }
        public string TemSom { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SysMaster.Models;
using System.Diagnostics;

namespace SysMaster.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StatusController.cs
using AForge.Video.DirectShow;
using Microsoft.AspNetCore.Mvc;
using SysMaster.Models;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Management;
using System.Media;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;

namespace SysMaster.Controllers {
    public class StatusController : Controller {
        public IActionResult Index() {
            var viewModel = new StatusViewModel();

            // Medição de hardware e software
            var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_Processor");
            foreach (var obj in searcher.Get()) {
                var cpu = (ManagementObject)obj;
                viewModel.CpuName = cpu["Name"].ToString();
                viewModel.CpuCores = int.Parse(cpu["NumberOfCores"].ToString());
            }

            //OS e Processador
            var os = Environment.OSVersion;
            viewModel.OsName = os.VersionString;
            viewModel.FrameworkVersion = RuntimeInformation.FrameworkDescription;

            //RAM
            var ramCounter = new PerformanceCounter("Memory", "Available Bytes");
            var ramValue = ramCounter.NextValue() / (1024 * 1024 * 1024); // em megabytes
            viewModel.RamMemory = ramValue.ToString("F2");


            //Download e Upload
            NetworkInterface[] interfaces = NetworkInterface.GetAllNetworkInterfaces();

            long bytesSent = 0;
            long bytesReceived = 0;

            foreach (NetworkInterface ni in interfaces) {
                bytesSent += ni.GetIPv4Statistics().BytesSent;
                bytesReceived += ni.GetIPv4Statistics().BytesReceived;
            }

            double downloadSpeed = (bytesReceived / 1024d) / 1024d / 1024d;
            double uploadSpeed = (bytesSent / 1024d) / 1024d / 1024d;

            viewModel.DownloadSpeed = downloadSpeed.ToString("0.00");
            viewModel.UploadSpeed = uploadSpeed.ToString("0.00");

            //Webcam
            // Obter todas as câmeras disponíveis
            var cameras = new FilterInfoCollection(FilterCategory.VideoInputDevice);

            if (cameras.Count == 0) {
                viewModel.Webcam = ("Não foi encontrada nenhuma câmera.");
            } else {
                Console.WriteLine("As seguintes câmeras foram encontradas:");
                foreach (FilterInfo camera in cameras) {
                    viewModel.Webcam = ("- " + camera.Name);
                }
            }

            //Nome da máquina
            var machineName = Environment.MachineName;
            viewModel.MaquinaNome = (machineName).ToString();

            //Endereço fisico da maquina
            var networkInterfaces = NetworkInterface.GetAllNetworkInterfaces();

            foreach (var networkInterface in networkInterfaces) {
                // check if network interface is Ethernet and it's operational
                if (networkInterface.NetworkInterfaceType == NetworkInterfaceType.Ethernet
                    && networkInterface.OperationalStatus == OperationalStatus.Up) {
                    var physicalAddress = networkInterface.GetPhysicalAddress();
                    viewModel.CaminhoFisico = (physicalAddress.ToString());
                }
            }

            //RAM instalada
            ManagementObjectSearcher s4 = new ManagementObjectSearcher("SELECT Capacity FROM Win32_PhysicalMemory");

            string resp = "0";
            double memoriaRam = 0;

            //Somando as mémorias
            foreach (ManagementObject mo in s4.Get()) {
                resp = Convert.ToString(mo["Capacity"]);
                memoriaRam += Convert.ToDouble(resp);
            }

            //Dividi 3 vezes por 1024 para pegar em gigas
            double memoriaRamTotal = 0;
            memoriaRamTotal = memoriaRam / 1024 / 1024 / 1024;

            viewModel.RamInstalada = "Memória RAM: " + memoriaRamTotal + " GB";

            //Espaço no disco
            DriveInfo[] allDrives = DriveInfo.GetDrives();

            foreach (DriveInfo c in allDrives) {
                if (c.IsReady == true) {
                    viewModel.DiscoDisponivel = ($"  Total available space: {(c.TotalFreeSpace / 1024 / 1024 / 1024)} GB");
                    viewModel.DiscoTotal = ($"  Total size of drive: {(c.TotalSize / 1024 / 1024 / 1024)} GB");
                }
            }

            //Verificar som
            SoundPlayer player = new SoundPlayer();
            try {
                player.SoundLocation = @"C:\Windows\Media\chimes.wav";
                player.Load();
                player.Play();
                viewModel.TemSom = ("OK");
            } catch (Exception ex) {
                viewModel.TemSom = ("Dipositivo sem saída de som: " + ex.Message);
            }

            //View
            return View(viewModel);

        }
    }

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"><a style="text-decoration:none;color:#A020F0;" asp-action="Index" asp-controller="Status"><strong>Syscheck</strong></a></h1>
    <p>Repositorio <a style="text-decoration:none;" target="_blank" href="https://github.com/D4nRossi/SysMaster">GitHub</a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SysMaster</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SysMaster.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid text-center">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SysMaster</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SysMaster - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Status/Index.cshtml
@model StatusViewModel
<div class="container">
    <h1>Syscheck</h1>
    <div class="row">
        <div class="col-6">
            <h4>CPU</h4>
            <p>@Model.CpuName</p>
            <h4>Download Speed</h4>
            <p>@Model.DownloadSpeed Mb/s</p>
            <h4>Saida de Som</h4>
            <p>@Model.TemSom</p>
            <h4>RAM livre</h4>
            <p>@Model.RamMemory GB</p>
            <h4>Nome da Máquina</h4>
            <p>@Model.MaquinaNome</p>
            <h4>Disco Disponivel</h4>
            <p>@Model.DiscoDisponivel</p>
            <h4>SO</h4>
            <p>@Model.OsName</p>
        </div>
        <div class="col-6">
            <h4>Nucleos</h4>
            <p>@Model.CpuCores</p>
            <h4>Upload Speed</h4>
            <p>@Model.UploadSpeed Mb/s</p>
            <h4>Tem Webcam</h4>
            <p>@Model.Webcam</p>
            <h4>RAM instalada</h4>
            <p>@Model.RamInstalada</p>
            <h4>Caminho Físico</h4>
            <p>@Model.CaminhoFisico</p>
            <h4>Disco Total</h4>
            <p>@Model.DiscoTotal</p>
        </div>
    </div>